version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: go_expert_sqlc_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courses
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"