apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: kcalixto/go-expert-k8s:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" # 500 millicores = 0.5 cores
        ports:
        - containerPort: 8080