services:
  # The zipkin process services the UI, and also exposes a POST endpoint that
  # instrumentation can send trace data to.
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to increase heap size
      # - JAVA_OPTS=-Xms128m -Xmx128m -XX:+ExitOnOutOfMemoryError
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
    # Uncomment to enable debug logging
    # command: --logging.level.zipkin2=DEBUG
  otel-collector:
    image: "otel/opentelemetry-collector-contrib:latest"
    container_name: otel-collector
    ports:
      - "55680:55680"
      - "4317:4317"
    volumes:
      - ./.docker/otel-collector-config.yaml:/otel-local-config.yaml
    command:
      - "--config=/otel-local-config.yaml"
    depends_on:
      - zipkin
  service-a:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        CMD_PATH: ./cmd/a
    ports:
      - "8080:8080"
    depends_on:
      - service-b
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
      - SERVICE_B_ENDPOINT=http://service-b:8081
  service-b:
    build:
      context: .
      dockerfile: build/Dockerfile
      args:
        CMD_PATH: ./cmd/b
    ports:
      - "8081:8081"
    environment:
      - ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - otel-collector
